import Foundation
import SwiftUI
import MapKit
import CoreLocation

// MARK: - Shared Models

/// Unit system for displaying values
enum UnitSystem: String, Codable {
    case metric
    case imperial

    /// Format a distance value (in meters) for display
    /// - Parameters:
    ///   - meters: Distance in meters
    ///   - decimals: Number of decimal places (default: 0)
    /// - Returns: Formatted string with appropriate unit suffix
    func formatDistance(_ meters: Double, decimals: Int = 0) -> String {
        switch self {
        case .imperial:
            return FormatUtils.formatMiles(meters / metersPerMile, decimals: decimals)
        case .metric:
            return FormatUtils.formatKilometers(meters / metersPerKm, decimals: decimals)
        }
    }

    /// Format an elevation value (in meters) for display
    /// - Parameter meters: Elevation in meters
    /// - Returns: Formatted string with appropriate unit suffix
    func formatElevation(_ meters: Double) -> String {
        switch self {
        case .imperial:
            return FormatUtils.formatFeet(meters * metersToFeet)
        case .metric:
            return FormatUtils.formatMeters(meters)
        }
    }

    /// The distance unit name for this system
    var distanceUnit: String {
        self == .imperial ? "mi" : "km"
    }

    /// The elevation unit name for this system
    var elevationUnit: String {
        self == .imperial ? "ft" : "m"
    }
}

/// Time frame for records
///
/// ## Daily Records Strategy
///
/// **Purpose:** Daily records provide fine-grained data for monthly charts in StatisticsView.
/// They are an internal implementation detail, NOT exposed to users in the UI.
///
/// **Lifecycle:**
/// 1. **Creation:** Generated by `RecordHistoryManager.updateAllDailyRecords()` which is called
///    from `RecordManager.updateDailyRecords()` each time a location update occurs
/// 2. **Storage:** Persisted in Core Data with `timeFrame = "Daily"`
/// 3. **Usage:** Loaded by `StatisticsView` to build day-by-day charts for "This Month" view
/// 4. **Cleanup:** Old daily records (>60 days) are deleted by `cleanupOldDailyRecords()`
///    which is called from `StatisticsView.onAppear` and after photo imports
///
/// **Why Hidden:**
/// - Users don't need to see "daily best" records - they care about monthly/yearly/lifetime
/// - Daily records are ephemeral - only kept for recent months to support charts
/// - Showing them would clutter the UI and confuse users
///
/// **Data Flow:**
/// ```
/// LocationUpdate → RecordManager.updateRecords()
///                → RecordManager.updateDailyRecords()
///                → RecordHistoryManager.updateAllDailyRecords()
///                → Core Data (timeFrame="Daily")
///                → StatisticsView.loadStatistics()
///                → Monthly charts
/// ```
/// NOTE: WidgetTimeFrame in GeoRecordsWidget.swift duplicates month/year/allTime cases.
/// When modifying these cases, update BOTH enums to stay in sync.
enum TimeFrame: String, CaseIterable {
    case daily = "Daily"      // Hidden daily extremes for chart granularity (see doc comment above)
    case month = "Monthly"    // Widget uses "This Month" display but matches this rawValue
    case year = "Yearly"      // Widget uses "This Year" display but matches this rawValue
    case allTime = "Lifetime" // Matches widget exactly

    /// Initialize from deep link URL parameter (e.g., "monthly", "yearly", "allTime")
    init?(deepLinkParam param: String) {
        switch param {
        case "monthly": self = .month
        case "yearly": self = .year
        case "allTime": self = .allTime
        default: return nil
        }
    }

    /// Display name for picker UI (e.g., "This Month" instead of "Monthly")
    var displayName: String {
        switch self {
        case .daily: return "Daily"  // Not shown in UI
        case .month: return "This Month"
        case .year: return "This Year"
        case .allTime: return "Lifetime"
        }
    }

    /// Label for record detail views (e.g., "Monthly Record")
    var recordLabel: String {
        "\(rawValue) Record"
    }

    /// Single-letter abbreviation for compact UI display
    var abbreviation: String {
        switch self {
        case .daily: return "D"
        case .month: return "M"
        case .year: return "Y"
        case .allTime: return "L"
        }
    }

    /// Color associated with this timeframe
    var color: Color {
        switch self {
        case .daily: return .gray
        case .month: return .green
        case .year: return .orange
        case .allTime: return .blue
        }
    }

    /// Sort order for displaying timeframes (Monthly first, then Yearly, then Lifetime)
    var sortOrder: Int {
        switch self {
        case .daily: return -1  // Not shown in UI
        case .month: return 0
        case .year: return 1
        case .allTime: return 2
        }
    }

    /// Whether this timeframe should be shown in the UI picker
    var isUserVisible: Bool {
        switch self {
        case .daily: return false
        case .month, .year, .allTime: return true
        }
    }

    /// User-visible timeframes for pickers
    static var userVisibleCases: [TimeFrame] {
        return allCases.filter { $0.isUserVisible }
    }
}

/// Record type enum for type safety and comparison logic.
/// NOTE: WidgetRecordType in GeoRecordsWidget.swift duplicates the geographic extreme cases.
/// When modifying north/south/east/west/up/fromHome cases, update BOTH enums to stay in sync.
enum RecordType: String, CaseIterable {
    case north = "Furthest North"
    case south = "Furthest South"
    case east = "Furthest East"
    case west = "Furthest West"
    case up = "Furthest Up"
    case fromHome = "Furthest from Home"
    case state = "New State"
    case country = "New Country"
    case continent = "New Continent"

    /// Whether this is a geographical extreme record (vs. region visit)
    var isGeographicExtreme: Bool {
        switch self {
        case .north, .south, .east, .west, .up, .fromHome:
            return true
        case .state, .country, .continent:
            return false
        }
    }

    /// Whether this is a region visit record
    var isRegionVisit: Bool {
        return !isGeographicExtreme
    }

    /// Whether this record type uses ascending comparison (higher is better)
    /// Only applies to geographic extremes
    var isAscending: Bool {
        switch self {
        case .north, .east, .up, .fromHome:
            return true  // Higher values are better
        case .south, .west:
            return false  // Lower values are better
        case .state, .country, .continent:
            return true  // Earlier timestamp is "better" (first visit)
        }
    }

    /// Determine if a new value should replace an existing record
    func shouldReplace(newValue: Double, oldValue: Double) -> Bool {
        return isAscending ? newValue > oldValue : newValue < oldValue
    }

    /// All record type strings for compatibility
    static var allTypeStrings: [String] {
        return RecordType.allCases.map { $0.rawValue }
    }

    /// Get record type from string (for backward compatibility)
    static func from(string: String) -> RecordType? {
        return RecordType.allCases.first { $0.rawValue == string }
    }
}

/// Region type for visited regions tracking
enum RegionType: String, CaseIterable, Codable {
    case state = "state"
    case country = "country"

    var displayName: String {
        switch self {
        case .state: return "State"
        case .country: return "Country"
        }
    }

    var pluralName: String {
        switch self {
        case .state: return "States"
        case .country: return "Countries"
        }
    }
}

/// Continent enum for continent-level tracking (derived from countries)
enum Continent: String, CaseIterable {
    case africa = "Africa"
    case antarctica = "Antarctica"
    case asia = "Asia"
    case europe = "Europe"
    case northAmerica = "North America"
    case oceania = "Australia / Oceania"
    case southAmerica = "South America"

    /// Total number of continents
    static var totalCount: Int { 7 }
}

/// Source for tracking how a record was added
enum RecordSource: String, Codable {
    case photo = "photo"
    case location = "location"
    case home = "home"
    case manual = "manual"

    /// User-friendly display name for the source
    var displayName: String {
        switch self {
        case .photo:
            return "Photo Library"
        case .location:
            return "Automatic"
        case .home:
            return "Home Location"
        case .manual:
            return "Manual Entry"
        }
    }
}

/// Legacy alias for backward compatibility
typealias VisitSource = RecordSource

// MARK: - Thresholds and Tolerances

/// Photo asset matching: threshold for matching photos by GPS location (in meters)
/// Used when identifiers don't match but timestamp and location do
let photoLocationMatchThresholdMeters: Double = 100.0

/// Photo asset matching: threshold for matching photos by timestamp (in seconds)
/// Photos within this time window are considered candidates for location matching
let photoTimestampMatchThresholdSeconds: TimeInterval = 2.0

/// Photo region processing: time window for avoiding duplicate processing (in seconds)
/// If a photo was processed within this window, skip it to avoid duplicates
let photoProcessingWindowSeconds: TimeInterval = 300 // 5 minutes

/// Duplicate record detection: time tolerance for considering records duplicates (in seconds)
let duplicateTimeToleranceSeconds: TimeInterval = 1.0

/// Duplicate record detection: value tolerance for numeric comparisons
let duplicateValueTolerance: Double = 0.0001

/// Duplicate record detection: coordinate tolerance for GPS location comparisons (in degrees)
/// ~11 meters at the equator
let duplicateCoordinateToleranceDegrees: Double = 0.0001

// MARK: - UserDefaults Keys

/// Type-safe keys for UserDefaults storage
enum UserDefaultsKey: String {
    // Setup
    case hasCompletedSetup

    // Notification settings
    case notifyOnMonthlyRecords
    case notifyOnYearlyRecords
    case notifyOnAllTimeRecords
    case notifyOnNewRegion
    case summaryNotificationsEnabled
    case photoPromptsEnabled

    // Inactivity reminder
    case inactivityReminderEnabled
    case inactivityReminderDays

    // Record thresholds
    case minLatitudeDelta
    case minLongitudeDelta
    case minAltitudeDeltaMetersImperial
    case minDistanceDeltaMetersImperial
    case minAltitudeDeltaMetersMetric
    case minDistanceDeltaMetersMetric

    // Home location
    case homeAddress
    case homeLocationName
    case homeLatitude
    case homeLongitude

    // Units
    case unitSystem

    // Wizard preferences
    case skippedWizardRecords  // Set of record keys that user chose to skip

    // Widget map regions (user-defined framing for widget maps)
    case widgetMapStatesLat
    case widgetMapStatesLon
    case widgetMapStatesLatDelta
    case widgetMapStatesLonDelta
    case widgetMapCountriesLat
    case widgetMapCountriesLon
    case widgetMapCountriesLatDelta
    case widgetMapCountriesLonDelta
    case widgetMapContinentsLat
    case widgetMapContinentsLon
    case widgetMapContinentsLatDelta
    case widgetMapContinentsLonDelta

    // Legacy keys (for migration)
    case notifyOnNewRecord  // Migrated to timeframe-specific settings
    case minAltitudeDeltaFeet  // Migrated to meters
    case minAltitudeDeltaMeters  // Migrated to unit-specific
    case minDistanceDeltaMeters  // Migrated to unit-specific
    case monthlySummaryEnabled  // Migrated to summaryNotificationsEnabled
    case yearlySummaryEnabled  // Migrated to summaryNotificationsEnabled
}

// MARK: - Debug Logging

/// Debug print that only outputs in DEBUG builds
func debugLog(_ items: Any..., separator: String = " ", terminator: String = "\n") {
    #if DEBUG
    print(items.map { "\($0)" }.joined(separator: separator), terminator: terminator)
    #endif
}

// MARK: - US State Codes

/// All 50 US state postal codes
let usStatePostalCodes: Set<String> = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
]

/// US territories and DC postal codes (tracked as states but not counted in "50 states")
let usTerritoryCodes: Set<String> = ["DC", "AS", "GU", "MP", "PR", "VI"]

/// All US state and territory codes combined
let allUSStateCodes: Set<String> = usStatePostalCodes.union(usTerritoryCodes)

/// Codes to exclude from "X of 50 states" count (both bare and US- prefixed versions)
let nonStateCodesForCount: Set<String> = {
    var codes = usTerritoryCodes
    for code in usTerritoryCodes {
        codes.insert("US-\(code)")
    }
    return codes
}()

/// Normalize a region code for US states to use "US-" prefix
/// Fixes backups and data that may have bare 2-letter state codes that collide with country codes
/// - Parameters:
///   - code: The region code to normalize (e.g., "AL", "US-AL", "FR")
///   - isState: Whether this is a state/territory record
/// - Returns: Normalized code (e.g., "AL" → "US-AL" for states, unchanged for countries)
func normalizeRegionCode(_ code: String, isState: Bool) -> String {
    // If it's a state with a bare 2-letter code that matches a US state, prefix it
    if isState && code.count == 2 && !code.hasPrefix("US-") && allUSStateCodes.contains(code) {
        return "US-\(code)"
    }
    return code
}

/// FIPS code to postal code mapping for US states and territories
let fipsToPostalCode: [String: String] = [
    "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA",
    "08": "CO", "09": "CT", "10": "DE", "11": "DC", "12": "FL",
    "13": "GA", "15": "HI", "16": "ID", "17": "IL", "18": "IN",
    "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME",
    "24": "MD", "25": "MA", "26": "MI", "27": "MN", "28": "MS",
    "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
    "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
    "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI",
    "45": "SC", "46": "SD", "47": "TN", "48": "TX", "49": "UT",
    "50": "VT", "51": "VA", "53": "WA", "54": "WV", "55": "WI",
    "56": "WY",
    // Territories
    "60": "AS", "66": "GU", "69": "MP", "72": "PR", "78": "VI"
]

// MARK: - TimeFrame String Variations

/// Historical variations of the "Lifetime" timeframe string stored in Core Data
/// Used for query predicates to match records regardless of which variation was used
let lifetimeTimeFrameVariations = ["Lifetime", "All-Time", "All Time"]

/// Canonical timeframe string for new records (always use this when saving)
let canonicalLifetimeTimeFrame = "Lifetime"

// MARK: - Territory Mappings

/// Territory codes mapped to their parent country code (for flag display)
/// These territories get their own card but display parent country's flag
let territoryToParentCountry: [String: String] = [
    // French territories → France (FR)
    "GF": "FR",   // French Guiana
    "MQ": "FR",   // Martinique
    "GP": "FR",   // Guadeloupe
    "RE": "FR",   // Réunion
    "YT": "FR",   // Mayotte
    "NC": "FR",   // New Caledonia
    "PF": "FR",   // French Polynesia

    // Portuguese territories → Portugal (PT)
    "PT-20": "PT",  // Azores
    "PT-30": "PT",  // Madeira

    // Spanish territories → Spain (ES)
    "ES-CN": "ES",  // Canary Islands

    // Dutch territories → Netherlands (NL)
    "CW": "NL",   // Curaçao
    "AW": "NL",   // Aruba
    "SX": "NL",   // Sint Maarten

    // British territories → United Kingdom (GB)
    "BM": "GB",   // Bermuda
    "VG": "GB",   // British Virgin Islands
    "KY": "GB",   // Cayman Islands
    "FK": "GB",   // Falkland Islands
    "SC": "GB",   // Seychelles
    "GI": "GB",   // Gibraltar

    // Danish territories → Denmark (DK)
    "FO": "DK",   // Faroe Islands
    "GL": "DK",   // Greenland

    // Australian territories → Australia (AU)
    "CX": "AU",   // Christmas Island
    "CC": "AU",   // Cocos (Keeling) Islands
    "NF": "AU",   // Norfolk Island

    // New Zealand territories → New Zealand (NZ)
    "CK": "NZ",   // Cook Islands
    "NU": "NZ",   // Niue
    "TK": "NZ",   // Tokelau
]

/// All territory codes (excluding US territories which are tracked as states)
let territoryCodes: Set<String> = Set(territoryToParentCountry.keys)

/// Check if a region code is a territory (not a sovereign country)
func isTerritory(_ code: String) -> Bool {
    return territoryCodes.contains(code)
}

/// Get the flag code for a region - returns parent country for territories
func flagCodeForRegion(_ regionCode: String) -> String? {
    // If it's a territory, return parent country code
    if let parentCode = territoryToParentCountry[regionCode] {
        return parentCode
    }
    // Otherwise return the code itself if it's a valid 2-letter code
    if regionCode.count == 2 {
        return regionCode
    }
    return nil
}

// MARK: - Unit Conversion Constants

/// Meters to feet conversion factor
let metersToFeet = 3.28084

/// Feet to meters conversion factor
let feetToMeters = 0.3048

/// Feet per mile
let feetPerMile = 5280.0

/// Meters per mile
let metersPerMile = 1609.344

/// Meters per kilometer
let metersPerKm = 1000.0

// MARK: - Photo Import Configuration

/// Maximum number of photos to consider per region during import
/// Higher values increase thoroughness but take longer to process
let maxPhotosPerRegionDuringImport = 50

/// Maximum number of candidate records to keep per time period during photo scanning
/// Limits memory usage during large photo library scans
let maxCandidatesPerTimeFrameDuringImport = 50

// MARK: - Region Tracking Configuration

/// Minimum distance threshold in meters for considering a location significant
/// Locations within this distance of a previous visit are considered the same place
let regionTrackingDistanceThresholdMeters: Double = 100.0

// MARK: - Distance Utilities

/// Calculates distance between two coordinates in meters
/// - Parameters:
///   - from: Starting coordinate
///   - to: Destination coordinate
/// - Returns: Distance in meters
func distanceBetween(from: CLLocationCoordinate2D, to: CLLocationCoordinate2D) -> Double {
    let fromLocation = CLLocation(latitude: from.latitude, longitude: from.longitude)
    let toLocation = CLLocation(latitude: to.latitude, longitude: to.longitude)
    return fromLocation.distance(from: toLocation)
}

/// Calculates the north-south great-circle distance component in meters
/// Positive = destination is north of origin, Negative = destination is south
/// - Parameters:
///   - from: Origin coordinate (typically home)
///   - to: Destination coordinate
/// - Returns: Signed distance in meters (positive = north, negative = south)
func northSouthDistance(from: CLLocationCoordinate2D, to: CLLocationCoordinate2D) -> Double {
    // Calculate distance along the meridian (same longitude, different latitude)
    let sameLogitude = CLLocationCoordinate2D(latitude: to.latitude, longitude: from.longitude)
    let distance = distanceBetween(from: from, to: sameLogitude)
    // Return positive if north, negative if south
    return to.latitude >= from.latitude ? distance : -distance
}

/// Calculates the east-west great-circle distance component in meters
/// Positive = destination is east of origin, Negative = destination is west
/// Uses the shorter path around the globe (handles antimeridian correctly)
/// Distance is calculated at the ORIGIN's latitude (consistent with N/S using origin's longitude)
/// - Parameters:
///   - from: Origin coordinate (typically home)
///   - to: Destination coordinate
/// - Returns: Signed distance in meters (positive = east, negative = west)
func eastWestDistance(from: CLLocationCoordinate2D, to: CLLocationCoordinate2D) -> Double {
    // Calculate distance along the parallel at the ORIGIN's latitude
    // This is consistent with N/S which uses the origin's longitude
    // Answers: "How far east/west would I travel along my home parallel to reach this longitude?"
    let destAtOriginLat = CLLocationCoordinate2D(latitude: from.latitude, longitude: to.longitude)
    let distance = distanceBetween(from: from, to: destAtOriginLat)

    // Determine direction (east or west) using the shorter path
    var lonDiff = to.longitude - from.longitude
    // Normalize to -180 to 180 range (handles antimeridian crossing)
    if lonDiff > 180 {
        lonDiff -= 360
    } else if lonDiff < -180 {
        lonDiff += 360
    }

    // Return positive if east, negative if west
    return lonDiff >= 0 ? distance : -distance
}

// MARK: - Geocoding Utilities

// MARK: - MapKit Constants

/// Default map zoom level for record details (~5km at equator)
let defaultMapLatDelta = 0.05
let defaultMapLonDelta = 0.05

/// Wide map zoom level for overview
let wideMapLatDelta = 2.0
let wideMapLonDelta = 2.0

/// Default map center for US states view (geographic center of contiguous US)
let defaultUSMapCenter = CLLocationCoordinate2D(latitude: 39.8283, longitude: -98.5795)
/// Default span for viewing a US state (fallback when polygon unavailable)
let defaultUSStateSpan = MKCoordinateSpan(latitudeDelta: 8, longitudeDelta: 10)

/// Default map center for world view (Atlantic-centered)
let defaultWorldMapCenter = CLLocationCoordinate2D(latitude: 20, longitude: 0)
/// Default span for viewing a country (fallback when polygon unavailable)
let defaultCountrySpan = MKCoordinateSpan(latitudeDelta: 15, longitudeDelta: 20)
/// Default span for viewing a continent
let defaultContinentSpan = MKCoordinateSpan(latitudeDelta: 60, longitudeDelta: 80)

// MARK: - UI Constants

/// Screen height threshold for compact layout (iPhone 14/15 and smaller)
let compactScreenHeightThreshold: CGFloat = 850

/// Height for card TabView pagers (Records tab, Maps tab)
let cardTabViewHeight: CGFloat = 280

// MARK: - Location Validation Constants

/// Threshold for detecting "Null Island" (0,0) coordinates - approximately 1km
let nullIslandCoordinateThreshold = 0.01

/// Threshold for detecting zero altitude at Null Island
let nullIslandAltitudeThreshold = 1.0

/// Threshold for filtering out records "at home" (in meters)
/// Records within this distance of home are considered bogus/test data
let atHomeRadiusMeters: Double = 100.0

/// Maximum realistic altitude on Earth (meters) - Mount Everest is 8,849m
let maxRealisticAltitudeMeters = 9000.0

/// Coordinate tolerance for location name proximity in degrees (approximately 11 meters)
/// Used for both looking up existing location names and propagating name changes
/// to all records at the "same" location
let locationNameProximityToleranceDegrees = 0.0001

// MARK: - Location Validation Utilities

/// Result of location validation
enum LocationValidationResult {
    case valid
    case nullIsland
    case unrealisticAltitude(meters: Double)
}

/// Validates a location for recording
/// - Parameters:
///   - latitude: The latitude coordinate
///   - longitude: The longitude coordinate
///   - altitude: The altitude in meters
/// - Returns: Validation result indicating if location is valid or why it's invalid
func validateLocation(latitude: Double, longitude: Double, altitude: Double) -> LocationValidationResult {
    // Check for "Null Island" (0,0 with ~0 altitude) - placeholder values for missing GPS
    let isNullIsland = abs(latitude) < nullIslandCoordinateThreshold &&
                       abs(longitude) < nullIslandCoordinateThreshold &&
                       abs(altitude) < nullIslandAltitudeThreshold
    if isNullIsland {
        return .nullIsland
    }

    // Check for unrealistic altitudes (above Mount Everest)
    if altitude > maxRealisticAltitudeMeters {
        return .unrealisticAltitude(meters: altitude)
    }

    return .valid
}

/// Validates a CLLocation for recording
/// - Parameter location: The location to validate
/// - Returns: Validation result indicating if location is valid or why it's invalid
func validateLocation(_ location: CLLocation) -> LocationValidationResult {
    return validateLocation(
        latitude: location.coordinate.latitude,
        longitude: location.coordinate.longitude,
        altitude: location.altitude
    )
}

// MARK: - String Constants

/// Default string for unknown/missing values
let unknownValueString = "Unknown"

/// Default string for unknown location
let unknownLocationString = "Unknown Location"

// MARK: - Threshold Constants

/// Batch save threshold for daily record operations
let dailyRecordBatchThreshold = 100

/// Geocoding throttle interval in seconds
let geocodingThrottleInterval: TimeInterval = 60

// MARK: - Time Constants

/// Seconds in one day
let secondsPerDay: TimeInterval = 86400

/// Seconds until end of day (used for date range calculations)
let secondsUntilEndOfDay: TimeInterval = 86399

/// Altitude threshold for showing altitude in detail views (meters)
let altitudeDisplayThreshold: Double = 100

/// Minimum distance threshold for displaying chart values (in miles/km)
/// Records closer than this to home are shown as "—" to filter noise
let chartMinDistanceThreshold: Double = 1.0

// MARK: - Photo Import Constants

/// Batch size for processing photos during library scan
let photoScanBatchSize = 100

/// Maximum number of photo candidates to display per record type in wizard
/// (limits UI rendering for performance with large photo libraries)
let wizardMaxCandidatesPerType = 50

/// Duration to suppress notifications after photo import (in seconds)
let postImportNotificationSuppressionSeconds: TimeInterval = 180

/// Same value in nanoseconds for Task.sleep
let postImportNotificationSuppressionNanoseconds: UInt64 = 180_000_000_000

// MARK: - Timing Constants

/// Brief pause for UI animations and state transitions (0.1 seconds)
let briefPauseNanos: UInt64 = 100_000_000

/// Short delay for UI feedback (0.3 seconds)
let shortDelayNanos: UInt64 = 300_000_000

/// Medium pause for transitions (0.5 seconds)
let mediumPauseNanos: UInt64 = 500_000_000

/// Standard delay for background operations (2 seconds)
let standardDelayNanos: UInt64 = 2_000_000_000

/// Extended delay to avoid conflicts with map rendering (8 seconds)
let mapGenerationDelayNanos: UInt64 = 8_000_000_000

/// Delay between geocoding requests to avoid rate limiting (1.5 seconds)
let geocodingDelayNanos: UInt64 = 1_500_000_000

// MARK: - Widget Dimensions

/// Standard size for widget map images (used by WidgetMapGenerator)
let widgetMapSize = CGSize(width: 680, height: 600)

/// Aspect ratio for widget maps (width / height)
let widgetMapAspectRatio: CGFloat = 680.0 / 600.0

// MARK: - Notification Identifiers

/// Notification identifier constants for consistent deduplication
enum NotificationIdentifier {
    static let monthlySummary = "monthly-summary"
    static let yearlySummary = "yearly-summary"
    static let inactivity = "inactivity"
    static let funFact = "fun-fact"

    /// Creates a notification identifier for a new record notification
    /// Using a consistent ID per record type allows deduplication
    /// - Parameter recordType: The RecordType enum case
    /// - Returns: A kebab-case identifier for the notification
    static func newRecord(for recordType: RecordType) -> String {
        return "new-record-\(recordType.rawValue.lowercased().replacingOccurrences(of: " ", with: "-"))"
    }

    /// Creates a notification identifier from a type string (for backward compatibility)
    /// - Parameter type: The record type string (e.g., "Furthest North")
    /// - Returns: A kebab-case identifier for the notification
    static func newRecord(type: String) -> String {
        if let recordType = RecordType.from(string: type) {
            return newRecord(for: recordType)
        }
        // Fallback for unknown types
        return "new-record-\(type.lowercased().replacingOccurrences(of: " ", with: "-"))"
    }
}

// MARK: - Date Formatters

/// Shared date formatter for detailed date display
let detailDateFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateStyle = .medium
    formatter.timeStyle = .medium
    return formatter
}()

/// Shared compact date formatter for history list
let compactDateFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "MM/dd/yy HH:mm"
    return formatter
}()

/// Shared medium date formatter (date only, no time)
let mediumDateFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateStyle = .medium
    return formatter
}()

/// ISO-style date formatter (yyyy-MM-dd) for compact displays
let isoDateFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "yyyy-MM-dd"
    return formatter
}()

/// Numeric date formatter (MM/dd/yyyy) for region records
let numericDateFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "MM/dd/yyyy"
    return formatter
}()

/// 24-hour time formatter (HH:mm) for compact displays
let time24Formatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "HH:mm"
    return formatter
}()

/// Full weekday date formatter (e.g., "Monday, January 15, 2025") for detail views
let fullWeekdayDateFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "EEEE, MMMM d, yyyy"
    return formatter
}()

/// 12-hour time formatter (e.g., "3:45 PM") for detail views
let time12Formatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "h:mm a"
    return formatter
}()

/// Date added formatter (e.g., "Jan 15, 2025 at 3:45 PM") for showing when records were added
let dateAddedFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "MMM d, yyyy 'at' h:mm a"
    return formatter
}()

/// Month name formatter (e.g., "January") for statistics
let monthNameFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "MMMM"
    return formatter
}()

/// Short month-year formatter (e.g., "Jan 2025") for chart labels
let shortMonthYearFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "MMM yyyy"
    return formatter
}()

/// EXIF date formatter for parsing photo metadata (format: "yyyy:MM:dd HH:mm:ss")
let exifDateFormatter: DateFormatter = {
    let formatter = DateFormatter()
    formatter.dateFormat = "yyyy:MM:dd HH:mm:ss"
    return formatter
}()

// MARK: - Date Extensions

extension Date {
    /// Returns the start of the current month and year for timeframe calculations
    static func timeFrameBoundaries() -> (month: Date, year: Date) {
        let calendar = Calendar.current
        let now = Date()
        let startOfMonth = calendar.dateInterval(of: .month, for: now)?.start ?? now
        let startOfYear = calendar.dateInterval(of: .year, for: now)?.start ?? now
        return (startOfMonth, startOfYear)
    }

    /// Returns the start date of the previous month or year (for summary calculations)
    /// - Parameter timeFrame: The time frame to get the previous period for
    /// - Returns: The start date of the previous period
    static func startOfPreviousPeriod(for timeFrame: TimeFrame) -> Date {
        let calendar = Calendar.current
        let now = Date()

        switch timeFrame {
        case .daily:
            let yesterday = calendar.date(byAdding: .day, value: -1, to: now) ?? now
            return calendar.startOfDay(for: yesterday)
        case .month:
            let lastMonth = calendar.date(byAdding: .month, value: -1, to: now) ?? now
            return calendar.dateInterval(of: .month, for: lastMonth)?.start ?? now
        case .year:
            let lastYear = calendar.date(byAdding: .year, value: -1, to: now) ?? now
            return calendar.dateInterval(of: .year, for: lastYear)?.start ?? now
        case .allTime:
            return Date.distantPast
        }
    }
}

// MARK: - Array Extensions

/// Safe array subscript that returns nil instead of crashing on out-of-bounds access
extension Array {
    subscript(safe index: Int) -> Element? {
        return indices.contains(index) ? self[index] : nil
    }
}

// MARK: - MapKit Extensions

extension MapCameraPosition {
    /// Creates a map camera position centered on a coordinate with standard zoom level
    /// - Parameters:
    ///   - coordinate: The coordinate to center on
    ///   - latitudeDelta: The latitude span (defaults to 0.05, about 5km)
    ///   - longitudeDelta: The longitude span (defaults to 0.05)
    /// - Returns: A MapCameraPosition centered on the coordinate
    static func centered(
        on coordinate: CLLocationCoordinate2D,
        latitudeDelta: Double = 0.05,
        longitudeDelta: Double = 0.05
    ) -> MapCameraPosition {
        return .region(MKCoordinateRegion(
            center: coordinate,
            span: MKCoordinateSpan(latitudeDelta: latitudeDelta, longitudeDelta: longitudeDelta)
        ))
    }
}
